### ISSUE TITLE
Auto-detect underlying type for static Any type

### ISSUE THREAD

**Issue by denis-zhdanov** [denis-zhdanov/kotlin-baker#18]
**Problem**

We might want to define a generic setup in the target data class, e.g. `data class Target(val data: Map<String, Any>`. Raw input might look like below:

```
data:
    key1:
        - listValue1
        - listValue2
    key2: simpleValue1
    key3:
        nestedKey1: mapValue1
        nestedKey2: mapValue2
```

In this situation, we want to create target instance like below:

```
Target(mapOf(
    "key1" to listOf("listValue1", "listValue2"),
    "key2" to "simpleValue1",
    "key3" to mapOf(
        "nestedKey1" to "mapValue1",
        "nestedKey2" to "mapValue2"
    )
))
```

**Task**

When target static type is defined as `Any`, be smart enough to pick it up as a `String`, `List<String>` or `Map<String, Any>`
